name: MAIN_PULL_REQUEST

on:
  pull_request: 
    branches: [develop, main]

jobs:
  MAIN_PULL_REQUEST:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/install-dep@main
      - name: lint 检查
        run: npm run lint