name: All_ON_PUSH

on: create

jobs:
  All_ON_PUSH:
    runs-on: ubuntu-latest
    if: github.event.ref_type == 'tag'
    steps:
      - uses: actions/setup-node@v2
      - uses: ./.github/actions/install-dep
      - run: npm run build
        shell: bash
      - name: release miniprogram
        uses: echoings/actions.mini-program@0.0.3
        with:
          project_type: miniprogram
          action_type: upload
          project_path: ./_example
          version: ${{ github.ref_name }}
        env: 
          MINI_APP_ID: ${{ secrets.APP_ID }}
          MINI_APP_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      - id: publish
        name: publish NPM
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
      - if: steps.publish.outputs.type != 'none'
        run: |
          echo "Version changed: ${{ steps.publish.outputs.old-version }} => ${{ steps.publish.outputs.version }}"

